
# services:
#   web:
#     build: .
#     image: ayomide/portfolio-option-a:latest
#     container_name: ayomide-portfolio-a
#     ports:
#       - "8080:80"
#     restart: unless-stopped

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "8080:80"
    restart: unless-stopped


# version: "3.9"

# services:
#   portfolio:
#     image: nginx:alpine
#     container_name: portfolio
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/usr/share/nginx/html
#     restart: unless-stopped

