
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ayomide-portfolio-a
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: your-domain.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ayomide-portfolio-a
                port:
                  number: 80
