# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ayomide-portfolio-a
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: ayomide-portfolio.local   # <-- update to your real domain
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: ayomide-portfolio-a
#                 port:
#                   number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ayomide-portfolio-a
spec:
  ingressClassName: nginx
  rules:
    - host: ayomide-portfolio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ayomide-portfolio-a
                port:
                  number: 80

