
apiVersion: v1
kind: Service
metadata:
  name: ayomide-portfolio-a
  labels:
    app: ayomide-portfolio-a
spec:
  type: ClusterIP
  selector:
    app: ayomide-portfolio-a
  ports:
    - name: http
      port: 80
      targetPort: 80
